### ISSUE TITLE
Cannot invoke "String.contains(java.lang.CharSequence)" because "message" is null

### ISSUE THREAD

**Issue by smscentras** [FancyMcPlugins/FancyNpcs#146]
```
[12:20:37 ERROR]: Could not pass event InventoryCloseEvent to nightcore v2.6.3
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "message" is null

        at de.oliver.fancyanalytics.api.FancyAnalyticsAPI.reportError(FancyAnalyticsAPI.java:193) ~[FancyNpcs-2.2.1.jar:?]
        at de.oliver.fancyanalytics.api.errors.GlobalExceptionHandler.publish(GlobalExceptionHandler.java:27) ~[FancyNpcs-2.2.1.jar:?]

        at java.util.logging.Logger.log(Logger.java:983) ~[?:?]
        at java.util.logging.Logger.doLog(Logger.java:1010) ~[?:?]
        at java.util.logging.Logger.log(Logger.java:1121) ~[?:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:70) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1637) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2938) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1430) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1418) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:365) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:349) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at su.nightexpress.nightcore.menu.MenuViewer.openInventory(MenuViewer.java:28) ~[nightcore-2.6.3.jar:?]
        at su.nightexpress.nightcore.menu.impl.AbstractMenu.open(AbstractMenu.java:171) ~[nightcore-2.6.3.jar:?]
        at su.nightexpress.ama.kit.menu.KitPreviewMenu.handleReturn(KitPreviewMenu.java:65) ~[AdvancedMobArena-7.18.0.jar:?]
        at su.nightexpress.ama.kit.menu.KitPreviewMenu.onClose(KitPreviewMenu.java:106) ~[AdvancedMobArena-7.18.0.jar:?]
        at su.nightexpress.nightcore.menu.MenuListener.onMenuClose(MenuListener.java:79) ~[nightcore-2.6.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1637) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2938) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1430) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1418) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:365) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:349) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at su.nightexpress.nightcore.menu.MenuViewer.openInventory(MenuViewer.java:28) ~[nightcore-2.6.3.jar:?]
        at su.nightexpress.nightcore.menu.impl.AbstractMenu.open(AbstractMenu.java:171) ~[nightcore-2.6.3.jar:?]
        at su.nightexpress.ama.kit.menu.KitPreviewMenu.handleReturn(KitPreviewMenu.java:65) ~[AdvancedMobArena-7.18.0.jar:?]
        at su.nightexpress.ama.kit.menu.KitPreviewMenu.onClose(KitPreviewMenu.java:106) ~[AdvancedMobArena-7.18.0.jar:?]
        at su.nightexpress.nightcore.menu.MenuListener.onMenuClose(MenuListener.java:79) ~[nightcore-2.6.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1637) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2938) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1430) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1418) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:365) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:349) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at su.nightexpress.nightcore.menu.MenuViewer.openInventory(MenuViewer.java:28) ~[nightcore-2.6.3.jar:?]
        at su.nightexpress.nightcore.menu.impl.AbstractMenu.open(AbstractMenu.java:171) ~[nightcore-2.6.3.jar:?]
        at su.nightexpress.ama.kit.menu.KitPreviewMenu.handleReturn(KitPreviewMenu.java:65) ~[AdvancedMobArena-7.18.0.jar:?]
        at su.nightexpress.ama.kit.menu.KitPreviewMenu.onClose(KitPreviewMenu.java:106) ~[AdvancedMobArena-7.18.0.jar:?]
        at su.nightexpress.nightcore.menu.MenuListener.onMenuClose(MenuListener.java:79) ~[nightcore-2.6.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]...
```

**Comment by OliverSchlueter** [comment]
Is fixed in the latest version
