### ISSUE TITLE
Paper StackTrace

### ISSUE THREAD

**Issue by Zemux1613** [FancyMcPlugins/FancyNpcs#150]
I had this StackTrace in my console when I joined my server.
Server Version 1.20.4
Java Version: 17

[14:33:32 WARN]: Exception in thread "Thread-10" java.lang.IllegalStateException: zip file closed
[14:33:32 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[14:33:32 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[14:33:32 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[14:33:32 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[14:33:32 WARN]:        at io.papermc.paper.plugin.entrypoint.classloader.PaperSimplePluginClassLoader.findClass(PaperSimplePluginClassLoader.java:62)
[14:33:32 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[14:33:32 WARN]:        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:114)
[14:33:32 WARN]:        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103)
[14:33:32 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[14:33:32 WARN]:        at FancyNpcs-2.2.1.jar//de.oliver.fancyanalytics.api.FancyAnalyticsAPI.send(FancyAnalyticsAPI.java:155)
[14:33:32 WARN]:        at FancyNpcs-2.2.1.jar//de.oliver.fancyanalytics.api.FancyAnalyticsAPI.lambda$initialize$0(FancyAnalyticsAPI.java:145)
[14:33:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by OliverSchlueter** [comment]
Try to use java 21
