### ISSUE TITLE
NoClassDefFoundError on Folia 1.21

### ISSUE THREAD

**Issue by ranminecraft** [FancyMcPlugins/FancyNpcs#154]
> [17:13:58 INFO]: Checking version, please wait...
[17:13:58 INFO]: This server is running Folia version 1.21-DEV-dev/1.21@2b8c879 (2024-08-06T17:56:07Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-90-dd11ef8 (MC: 1.21)
> ver FancyNpcs
[17:14:02 INFO]: FancyNpcs version 2.2.1
[17:14:02 INFO]: Simple, lightweight and fast NPC plugin using packets

```
[17:10:33 ERROR]: [FancyNpcs] Error initializing plugin 'FancyNpcs-2.2.1.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/level/ServerPlayer
        at FancyNpcs-2.2.1.jar/de.oliver.fancynpcs.FancyNpcs.onLoad(FancyNpcs.java:90) ~[FancyNpcs-2.2.1.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:552) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.level.ServerPlayer
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 10 more
```

**Comment by OliverSchlueter** [comment]
You need to get a **mojang mapped** jar of Folia

**Comment by ranminecraft** [comment]
> You need to get a **mojang mapped** jar of Folia

Thanks
