### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by tomasalias** [FancyMcPlugins/FancyNpcs#163]
[22:19:50 ERROR]: [FancyNpcs] Error initializing plugin 'FancyNpcs-2.2.2.186.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/level/Level
        at FancyNpcs-2.2.2.186.jar/de.oliver.fancynpcs.FancyNpcs.onLoad(FancyNpcs.java:99) ~[FancyNpcs-2.2.2.186.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:552) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.Level
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[folia-1.21.1.jar:1.21.1-DEV-a696d63]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 10 more

**Comment by OliverSchlueter** [comment]
You need to use a mojang mapped version of Folia

**Comment by tomasalias** [comment]
> You need to use a mojang mapped version of Folia

@OliverSchlueter Do you have one? Mine isn't working.
