### ISSUE TITLE
HTTP response code 524 from hangar

### ISSUE THREAD

**Issue by Obeeyyyy** [FancyMcPlugins/FancyNpcs#212]
[23:15:55 WARN]: java.io.IOException: Server returned HTTP response code: 524 for URL: https://hangar.papermc.io/api/v1/projects/FancyNpcs/latestrelease
[23:15:55 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998)
[23:15:55 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[23:15:55 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[23:15:55 WARN]:        at FancyNpcs-2.4.1.jar//de.oliver.fancylib.versionFetcher.VersionFetcher.getDataFromUrl(VersionFetcher.java:22)
[23:15:55 WARN]:        at FancyNpcs-2.4.1.jar//de.oliver.fancylib.versionFetcher.HangarVersionFetcher.fetchNewestVersion(HangarVersionFetcher.java:19)
[23:15:55 WARN]:        at FancyNpcs-2.4.1.jar//de.oliver.fancylib.versionFetcher.MasterVersionFetcher.fetchNewestVersion(MasterVersionFetcher.java:24)
[23:15:55 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:15:55 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:15:55 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[23:15:55 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[23:15:55 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[23:15:55 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[23:15:55 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

Seems like paper is having issues responding to the request, maybe catch this and output a better looking message
Same for FancyHolograms

**Comment by Zemux1613** [comment]
Same issue by using ``/rl confirm``


```
[23:31:11] [Server thread/INFO]: [FancyNpcs] Enabling FancyNpcs v2.4.1
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: java.io.IOException: Server returned HTTP response code: 503 for URL: https://hangar.papermc.io/api/v1/projects/FancyNpcs/latestrelease
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2014)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1615)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at FancyNpcs-2.4.1.jar//de.oliver.fancylib.versionFetcher.VersionFetcher.getDataFromUrl(VersionFetcher.java:22)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at FancyNpcs-2.4.1.jar//de.oliver.fancylib.versionFetcher.HangarVersionFetcher.fetchNewestVersion(HangarVersionFetcher.java:19)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at FancyNpcs-2.4.1.jar//de.oliver.fancylib.versionFetcher.MasterVersionFetcher.fetchNewestVersion(MasterVersionFetcher.java:24)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1804)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034)
[23:31:11] [ForkJoinPool.commonPool-worker-53/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
```

**Comment by OakLoaf** [comment]
This is not an issue of concern, it just means the plugin update checker was unable to reach hangar's API

**Comment by Obeeyyyy** [comment]
Yes i know, i suggested to handle the error differently so it does not print the exception into the console.

**Comment by Matt-MX** [comment]
Honestly not a bad idea, we should probably just log that it's unableto reach hangar instead of printing a whole stacktrace
