### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by xyfwdy** [FancyMcPlugins/FancyNpcs#49]
This server is running Folia version git-Folia-"edafbce" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: edafbce)
You are running the latest version
Previous version: git-Folia-"372d479" (MC: 1.20.1)

```
[FancyNpcs] Async task for FancyNpcs v2.0.3 generated an exception
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:233) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:142) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at de.oliver.fancynpcs.tracker.NpcTracker.run(NpcTracker.java:70) ~[FancyNpcs-2.0.3.jar:?]
	at de.oliver.fancylib.serverSoftware.schedulers.FoliaScheduler.lambda$runTaskTimerAsynchronously$7(FoliaScheduler.java:60) ~[FancyNpcs-2.0.3.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by OliverSchlueter** [comment]
Should be fixed in build 43 https://fancyplugins.de/fancynpcs/download/
