### ISSUE TITLE
Can't run 2.0.4

### ISSUE THREAD

**Issue by casadaycarson** [FancyMcPlugins/FancyNpcs#52]
[10:07:09] [Server thread/ERROR]: Could not load 'plugins/FancyNpcs-2.0.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: io/papermc/paper/plugin/configuration/PluginMeta
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:437) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3908-Spigot-e0e223f-b3efca5]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3908-Spigot-e0e223f-b3efca5]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3908-Spigot-e0e223f-b3efca5]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3908-Spigot-e0e223f-b3efca5]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/papermc/paper/plugin/configuration/PluginMeta
        at de.oliver.fancylib.serverSoftware.ServerSoftware.isFolia(ServerSoftware.java:15) ~[?:?]
        at de.oliver.fancynpcs.FancyNpcs.<init>(FancyNpcs.java:58) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:306) ~[?:?]
        at java.lang.Class.newInstance(Class.java:684) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: io.papermc.paper.plugin.configuration.PluginMeta
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at de.oliver.fancylib.serverSoftware.ServerSoftware.isFolia(ServerSoftware.java:15) ~[?:?]
        at de.oliver.fancynpcs.FancyNpcs.<init>(FancyNpcs.java:58) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]

**Comment by casadaycarson** [comment]
I didn't realize this plugin required paper. After replacing my spigot jars with paper this works.
