### ISSUE TITLE
Async task for FancyNpcs v2.0.4

### ISSUE THREAD

**Issue by ranminecraft** [FancyMcPlugins/FancyNpcs#54]
It only happen in folia 1.20.1. But folia 1.20.2 is fine.

This server is running Folia version git-Folia-"edafbce" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: edafbce)
You are running the latest version
Previous version: git-Folia-"372d479" (MC: 1.20.1)
```
[06:55:13] [Folia Async Scheduler Thread #7/WARN]: [FancyNpcs] Async task for FancyNpcs v2.0.4 generated an exception
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:233) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:142) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at de.oliver.fancynpcs.tracker.NpcTracker.run(NpcTracker.java:62) ~[FancyNpcs-2.0.4.jar:?]
	at de.oliver.fancylib.serverSoftware.schedulers.FoliaScheduler.lambda$runTaskTimerAsynchronously$7(FoliaScheduler.java:60) ~[FancyNpcs-2.0.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[06:55:13] [Folia Async Scheduler Thread #7/WARN]: [FancyNpcs] Async task for FancyNpcs v2.0.4 generated an exception
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:233) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:142) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at de.oliver.fancynpcs.tracker.NpcTracker.run(NpcTracker.java:62) ~[FancyNpcs-2.0.4.jar:?]
	at de.oliver.fancylib.serverSoftware.schedulers.FoliaScheduler.lambda$runTaskTimerAsynchronously$7(FoliaScheduler.java:60) ~[FancyNpcs-2.0.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by xyfwdy** [comment]
> Should be fixed in build 43 https://fancyplugins.de/fancynpcs/download/
```

[FancyNpcs] Async task for FancyNpcs v2.0.5-alpha1 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1633) ~[?:?]
	at de.oliver.fancynpcs.tracker.NpcTracker.run(NpcTracker.java:26) ~[FancyNpcs-2.0.5-alpha1.jar:?]
	at de.oliver.fancylib.serverSoftware.schedulers.FoliaScheduler.lambda$runTaskTimerAsynchronously$7(FoliaScheduler.java:60) ~[FancyNpcs-2.0.5-alpha1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by Grabsky** [comment]
@ranminecraft Can you try with FancyNpcs 2.4.0? Recently tried the plugin on Folia 1.20.6 and there were no errors in the console.

**Comment by OliverSchlueter** [comment]
Can't reproduce, reopen this issue, if it still happens in the latest version.
