### ISSUE TITLE
【BUG】After clicking on an NPC, an error is reported in the console

### ISSUE THREAD

**Issue by guoguoguofruit** [FancyMcPlugins/FancyNpcs#71]
After clicking on an NPC, an error is reported in the console

server version
[18:48:45 INFO]: This server is running Kaiiju version git-Kaiiju-"ad96ea2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: ad96ea2 on ver/1.20.1)
You are 1 version(s) behind
Download the new version at: https://github.com/KaiijuMC/Kaiiju/releases

chlick NPC error
[18:49:31 ERROR]: Could not pass event PlayerUseUnknownEntityEvent to FancyNpcs v2.0.6
java.lang.NoSuchMethodError: 'org.bukkit.util.Vector com.destroystokyo.paper.event.player.PlayerUseUnknownEntityEvent.getClickedRelativePosition()'
        at de.oliver.fancynpcs.listeners.PlayerUseUnknownEntityListener.onPlayerUseUnknownEntity(PlayerUseUnknownEntityListener.java:18) ~[FancyNpcs-2.0.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor161.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:git-Kaiiju-"ad96ea2"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:68) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.callPlayerUseUnknownEntityEvent(ServerGamePacketListenerImpl.java:3015) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:3007) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2994) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:52) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:75) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"ad96ea2"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
>

**Comment by OliverSchlueter** [comment]
Try to update Kaiiju, it needs to have the latest 1.20.1 paper patches (at least this patch https://github.com/PaperMC/paper/commit/eb8f2bb2a183746381738b5ccf08d209efa542b8)

**Comment by guoguoguofruit** [comment]
> 尝试更新 Kaiiju，它需要有最新的 1.20.1 纸补丁（至少这个补丁 [PaperMC/Paper@eb8f2bb](https://github.com/PaperMC/Paper/commit/eb8f2bb2a183746381738b5ccf08d209efa542b8))

But there are some serious bugs in the version after kaiiju#237, so I can't update kaiiju....

**Comment by OliverSchlueter** [comment]
Well FancyNpcs only supports the latest version of paper and folia, so the only suggestion is to update the server version.
